MVC_PortalePoliziaDiStato/Controllers/CompilazioneVerbaleController.cs
using MVC_PortalePoliziaDiStato.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Web.Mvc;

namespace MVC_PortalePoliziaDiStato.Controllers
{
    public class CompilazioneVerbaleController : Controller
    {
        // GET: CompilazioneVerbale
        //public ActionResult Index()
        //{
        //    return View();
        //}

        // GET: CompilazioneVerbale/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        // GET: CompilazioneVerbale/Create


        // questa action viene richiamata quando si clicca sul bottone "Compila Verbale" nella navbar.
        // La navbar è resa visibile solo se l'utente è loggato. e quin di esiste una Session "DatiAgenteLoggato"
        // in questo metodo sono stati utilizzati due dizionari per metere in relazione tra di loro l'IDviolazione e la sua descrizione,
        // il dizionario viene poi inserito in una viewbag e richiamato nella view Create. il dizionario è infine utilizzato per popolare una dropdownlist
        // discorso spessochè uguale per quanto riguarda il dizionario utilizzato per popolare la dropdownlist con le anagrafiche.
        // unica differenza è che in questo caso è stato utilizzato un model per salvare nome cognome dell utente selezionato e da questi due valori creare una proprietà nome completo che viene utilizzato nel dizionario come value da visualizzare nel render della view Create.
        public ActionResult Create()
        {

            if (Session["DatiAgenteLoggato"] != null)
            {
                string connectionString = ConfigurationManager.ConnectionStrings["connectionStringDb"].ToString();
                SqlConnection conn = new SqlConnection(connectionString);

                //List<int> ListaElencoViolazioni = new List<int>();
                Dictionary<int, string> DizionarioElencoViolazioni = new Dictionary<int, string>();
                Dictionary<int, ModelloNomeCompleto> DizionarioElencoAnagrafiche = new Dictionary<int, ModelloNomeCompleto>();
                //List<int> ListaIdAnagrafica = new List<int>();
                string query;

                try
                {
                    conn.Open();
                    //query = "SELECT IDViolazione FROM Violazione";
                    query = "SELECT * FROM Violazione";
                    SqlCommand cmd = new SqlCommand(query, conn);
                    SqlDataReader reader = cmd.ExecuteReader();

                    while (reader.Read())
                    {
                        int idViolazione = Convert.ToInt32(reader["IDViolazione"]);
                        string descrizione = reader["descrizione"].ToString();
                        //ListaElencoViolazioni.Add(idViolazione);
                        //Session["ListaElencoViolazioni"] = ListaElencoViolazioni;
                        DizionarioElencoViolazioni.Add(idViolazione, descrizione);
                    }

                    reader.Close();

                    query = "SELECT idanagrafica , nome , cognome FROM anagrafica order by idanagrafica ASC ";
                    cmd = new SqlCommand(query, conn); // Crea un nuovo comando SQL
                    reader = cmd.ExecuteReader(); // Esegui il nuovo comando SQL


                    while (reader.Read())
                    {
                        int idanagrafica = Convert.ToInt32(reader["IDAnagrafica"]);
                        string nome = reader["Nome"].ToString();
                        string cognome = reader["Cognome"].ToString();
                        //ListaIdAnagrafica.Add(idanagrafica);
                        //Session["ListaIdAnagrafica"] = ListaIdAnagrafica;
                        ModelloNomeCompleto Nome_CognomeCompleto = new ModelloNomeCompleto { Nome = nome, Cognome = cognome };
                        DizionarioElencoAnagrafiche.Add(idanagrafica, Nome_CognomeCompleto);
                    }

                    reader.Close();
                }
                catch (Exception ex)
                {
                    Response.Write(ex.Message);
                    //TempData["Errore"] = ex.Message;
                    //return RedirectToAction("Index");
                    return new EmptyResult();
                }
                finally
                {
                    conn.Close();
                }

                ViewBag.dizionarioViolazioni = DizionarioElencoViolazioni;
                ViewBag.dizionarioAnagrafiche = DizionarioElencoAnagrafiche;
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }




        }


        // tramite questo metodo vengono inseriti i dati del verbale nel database.
        [HttpPost]
        public ActionResult Create(Verbale verbale)
        {

            if (ModelState.IsValid)
            {
                string connectionString = ConfigurationManager.ConnectionStrings["connectionStringDb"].ToString();
                SqlConnection conn = new SqlConnection(connectionString);

                string query;

                try
                {
                    conn.Open();
                    query = "INSERT INTO Verbale (DataViolazione, IndirizzoViolazione, NominativoAgente, DataTrascrizione_verbale, Importo, DecurtamentoPunti, IDViolazione, IDAnagrafica) " +
                        "VALUES (@DataViolazione, @IndirizzoViolazione, @NominativoAgente, @DataTrascrizione_verbale, @Importo, @DecurtamentoPunti, @IDViolazione, @IDAnagrafica)";
                    SqlCommand cmd = new SqlCommand(query, conn);
                    cmd.Parameters.AddWithValue("@DataViolazione", Convert.ToDateTime(verbale.DataViolazione));
                    cmd.Parameters.AddWithValue("@IndirizzoViolazione", verbale.IndirizzoViolazione);
                    cmd.Parameters.AddWithValue("@NominativoAgente", verbale.NominativoAgente);
                    cmd.Parameters.AddWithValue("@DataTrascrizione_verbale", Convert.ToDateTime(verbale.DataTrascrizione_verbale));
                    cmd.Parameters.AddWithValue("@Importo", Convert.ToDecimal(verbale.Importo));
                    cmd.Parameters.AddWithValue("@DecurtamentoPunti", Convert.ToInt32(verbale.DecurtamentoPunti));
                    cmd.Parameters.AddWithValue("@IDViolazione", Convert.ToInt32(verbale.IDViolazione));
                    cmd.Parameters.AddWithValue("@IDAnagrafica", Convert.ToInt32(verbale.IDAnagrafica));

                    cmd.ExecuteNonQuery();

                    TempData["Messaggio"] = "Verbale Inserito Correttamente";
                    return RedirectToAction("Create");
                }
                catch (Exception ex)
                {
                    Response.Write(ex.Message);
                    TempData["Errore"] = ex.Message;
                    return RedirectToAction("Create");
                }
                finally
                {
                    conn.Close();
                }
            }
            else
            {
                TempData["Errore"] = "Errore di validazione. Ricontrolla i Campi.";
                return View("Create");
            }

        }




        // GET: CompilazioneVerbale/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: CompilazioneVerbale/Edit/5
        //[HttpPost]
        //public ActionResult Edit(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add update logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: CompilazioneVerbale/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: CompilazioneVerbale/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

MVC_PortalePoliziaDiStato/Controllers/VerbaliController.cs
using MVC_PortalePoliziaDiStato.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Web.Mvc;

namespace MVC_PortalePoliziaDiStato.Controllers
{
    public class VerbaliController : Controller
    {

        // l'utente può accedere a questa pagina solo se risulta essere loggato in quanto agente di polizia.
        public ActionResult Index()
        {
            if (Session["DatiAgenteLoggato"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }


        }

        // get che mostra i verbali raggruppati per trasgressore, questi vengono salvati in una lista di oggetti di tipo VerbaliRaggruppatiPerTrasgressori e passati alla view.
        public ActionResult VerbaliRaggruppatiTrasgressore()
        {
            string connectionString = ConfigurationManager.ConnectionStrings["connectionStringDb"].ToString();
            SqlConnection conn = new SqlConnection(connectionString);
            string query;

            List<VerbaliRaggruppatiPerTrasgressori> LIstaDeiVerbaliRaggrup_Trasgressori = new List<VerbaliRaggruppatiPerTrasgressori>();


            try
            {

                conn.Open();
                query = "SELECT Cognome, Nome, COUNT(*) AS NumeroVerbali, SUM(Importo) AS TotaleImporti, SUM(DecurtamentoPunti) AS TotalePunti FROM Anagrafica INNER JOIN Verbale ON Anagrafica.IdAnagrafica = Verbale.IDAnagrafica GROUP BY Cognome, Nome ORDER BY cognome ASC";
                SqlCommand cmd = new SqlCommand(query, conn);
                SqlDataReader reader = cmd.ExecuteReader();

                while (reader.Read())
                {
                    string CognomeTrasgressore = reader["Cognome"].ToString();
                    string NomeTrasgressore = reader["Nome"].ToString();
                    int NumeroVerbali = Convert.ToInt32(reader["NumeroVerbali"]);
                    //decimal TotaleImporti = Convert.ToDecimal(reader["TotaleImporti"]);
                    //int TotalePunti = Convert.ToInt32(reader["TotalePunti"]);

                    LIstaDeiVerbaliRaggrup_Trasgressori.Add(new VerbaliRaggruppatiPerTrasgressori(CognomeTrasgressore, NomeTrasgressore, NumeroVerbali));


                }
            }
            catch (Exception ex)
            {
                Response.Write(ex.Message);
                TempData["Errore"] = ex.Message;
                return RedirectToAction("Index");
            }
            finally
            {
                conn.Close();
            }

            return View(LIstaDeiVerbaliRaggrup_Trasgressori);
        }

        // get che mostra i verbali raggruppati per violazione, questi vengono salvati in una lista di oggetti di tipo VerbaliRaggruppatiPerViolazione e passati alla view.
        public ActionResult TotalePuntiDecurtati_PerTrasgressore()
        {
            string connectionString = ConfigurationManager.ConnectionStrings["connectionStringDb"].ToString();
            SqlConnection conn = new SqlConnection(connectionString);
            string query;

            List<TotalePuntiDecurtati_PerTrasgressore> ListaTotalePuntiDecurtati_Trasgressore = new List<TotalePuntiDecurtati_PerTrasgressore>();


            try
            {

                conn.Open();
                query = "SELECT Cognome, Nome, SUM(DecurtamentoPunti) AS TotalePunti FROM Anagrafica INNER JOIN Verbale ON Anagrafica.IdAnagrafica = Verbale.IDAnagrafica GROUP BY Cognome, Nome";
                SqlCommand cmd = new SqlCommand(query, conn);
                SqlDataReader reader = cmd.ExecuteReader();

                while (reader.Read())
                {
                    string CognomeTrasgressore = reader["Cognome"].ToString();
                    string NomeTrasgressore = reader["Nome"].ToString();
                    int SommaPuntiDecurtati = Convert.ToInt32(reader["TotalePunti"]);


                    ListaTotalePuntiDecurtati_Trasgressore.Add(new TotalePuntiDecurtati_PerTrasgressore(CognomeTrasgressore, NomeTrasgressore, SommaPuntiDecurtati));


                }
            }
            catch (Exception ex)
            {
                Response.Write(ex.Message);
                TempData["Errore"] = ex.Message;
                return RedirectToAction("Index");
            }
            finally
            {
                conn.Close();
            }

            return View(ListaTotalePuntiDecurtati_Trasgressore);
        }

        // get che mostra i verbali con importo maggiore di 400 euro, questi vengono salvati in una lista di oggetti di tipo verbaliImportoMagg400 e passati alla view.
        public ActionResult VerbaliImportoMaggiore400()
        {
            string connectionString = ConfigurationManager.ConnectionStrings["connectionStringDb"].ToString();
            SqlConnection conn = new SqlConnection(connectionString);
            string query;

            List<verbaliImportoMagg400> ListaVerbaliImportoMagg400 = new List<verbaliImportoMagg400>();

            try
            {

                conn.Open();
                query = "SELECT an.NOME , an.cognome , ve.importo , vio.descrizione FROM anagrafica as an inner join verbale as ve " +
                    "on ve.idanagrafica = an.IdAnagrafica inner join violazione as vio on ve.IDViolazione = vio.IDViolazione where ve.importo > 400";
                SqlCommand cmd = new SqlCommand(query, conn);
                SqlDataReader reader = cmd.ExecuteReader();

                while (reader.Read())
                {
                    string nome = reader["Nome"].ToString();
                    string cognome = reader["Cognome"].ToString();
                    decimal importo = Convert.ToDecimal(reader["Importo"]);
                    string descrizione = reader["Descrizione"].ToString();

                    ListaVerbaliImportoMagg400.Add(new verbaliImportoMagg400(nome, cognome, importo, descrizione));
                }
            }
            catch (Exception ex)
            {
                Response.Write(ex.Message);
                TempData["Errore"] = ex.Message;
                return RedirectToAction("Index");
            }
            finally
            {
                conn.Close();
            }


            return View(ListaVerbaliImportoMagg400);
        }

        // get che mostra i verbali con decurtamento punti maggiore di 10, questi vengono salvati in una lista di oggetti di tipo ViolazioniMagg10Pt e passati alla view.
        public ActionResult verbaliViolazioni10Pt()
        {

            string connectionString = ConfigurationManager.ConnectionStrings["connectionStringDb"].ToString();
            SqlConnection conn = new SqlConnection(connectionString);
            string query;

            //failistanza di una lista di oggetti di tipo verbaliViolazioni10Pt
            List<ViolazioniMagg10Pt> ListaViolazioniMagg10Pt = new List<ViolazioniMagg10Pt>();
            try
            {

                conn.Open();
                query = "SELECT ana.nome , ana.cognome , verb.importo , verb.DataViolazione , verb.DecurtamentoPunti " +
                    "FROM Anagrafica as ana inner join verbale as verb on ana.IdAnagrafica = verb.IDAnagrafica " +
                    "WHERE DecurtamentoPunti >= 10";

                SqlCommand cmd = new SqlCommand(query, conn);
                SqlDataReader reader = cmd.ExecuteReader();

                while (reader.Read())
                {
                    string nome = reader["Nome"].ToString();
                    string cognome = reader["Cognome"].ToString();
                    decimal importo = Convert.ToDecimal(reader["Importo"]);
                    DateTime DataViolazione = Convert.ToDateTime(reader["DataViolazione"]);
                    int DecurtamentoPunti = Convert.ToInt32(reader["DecurtamentoPunti"]);

                    ListaViolazioniMagg10Pt.Add(new ViolazioniMagg10Pt(nome, cognome, importo, DataViolazione, DecurtamentoPunti));
                }
            }
            catch (Exception ex)
            {
                Response.Write(ex.Message);
                TempData["Errore"] = ex.Message;
                return RedirectToAction("Index");
            }
            finally
            {
                conn.Close();
            }
            return View(ListaViolazioniMagg10Pt);
        }
    }
}

MVC_PortalePoliziaDiStato/Views/CompilazioneVerbale/Create.cshtml
@model MVC_PortalePoliziaDiStato.Models.Verbale

@{
    ViewBag.Title = "Create";
}





<div class="container">
    <div class="row">
        
        @Html.Partial("_AlertPartial")

        <div class="col-10">
            <h2>Nuovo Verbale</h2>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    @*<div class="form-group">
                            @Html.LabelFor(model => model.IdVerbale, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.IdVerbale, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.IdVerbale, "", new { @class = "text-danger" })
                            </div>
                        </div>*@



                    <div class="form-group">
                        @Html.LabelFor(model => model.DataViolazione, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DataViolazione, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DataViolazione, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.IndirizzoViolazione, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.IndirizzoViolazione, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.IndirizzoViolazione, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.NominativoAgente, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.NominativoAgente, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NominativoAgente, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DataTrascrizione_verbale, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DataTrascrizione_verbale, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DataTrascrizione_verbale, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Importo, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Importo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Importo, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DecurtamentoPunti, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DecurtamentoPunti, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DecurtamentoPunti, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.IDViolazione, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.IDViolazione, new SelectList((Dictionary<int, string>)ViewBag.dizionarioViolazioni, "Key", "Value"), "Seleziona una Violazione", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.IDViolazione, "", new { @class = "text-danger" })
                        </div>
                    </div>



                    <div class="form-group">
                        @Html.LabelFor(model => model.IDAnagrafica, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.IDAnagrafica, new SelectList((Dictionary<int, MVC_PortalePoliziaDiStato.Models.ModelloNomeCompleto>)ViewBag.dizionarioAnagrafiche, "Key", "Value.NomeCompleto"), "Seleziona un Cattivone", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.IDAnagrafica, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group my-3">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Crea Nuovo verbale" class="btn btn-outline-primary" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Back to List", "Index", "Verbali")
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        function hideAlertAfterThreeSeconds() {
            setTimeout(function () {
                $('.alert').fadeOut('slow');
            }, 3000);
        }
        $(document).ready(function () {
            hideAlertAfterThreeSeconds();
        });
    </script>

}

MVC_PortalePoliziaDiStato/Views/CompilazioneVerbale/_AlertPartial.cshtml
@if (TempData["Errore"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["Errore"]
    </div>
}

@if (TempData["Messaggio"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Messaggio"]
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
    function hideAlertAfterThreeSeconds() {
        setTimeout(function () {
            $('.alert').fadeOut('slow');
        }, 3000);
    }
    $(document).ready(function () {
        hideAlertAfterThreeSeconds();
    });
    </script>

}